[project]
name = "flight-tower-backend"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "geopy",
    "geocoder",
    "flightradarapi",
    "httpx",
    "pydantic",
    "pydantic-settings",
]
